name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    name: Build for push
    uses: ./.github/workflows/action-build.yaml
    with:
      version-postfix: "-dev"

  build-for-pr:
    if: ${{ github.event_name == 'pull_request' }}
    name: Build for pull request
    uses: ./.github/workflows/action-build.yaml
    with:
      version-postfix: "-pr${{ github.event.number }}"
