name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/action-build.yaml
    with:
      version-postfix: "-master"
      web-path-root: /${{ github.event.repository.name }}/

  github-pages:
    needs: [build]
    name: Deploy Github Pages
    uses: ./.github/workflows/action-gh-page.yaml
    with:
      artifact-name: web
      file-name: dist.tar.gz
      path-name: dist
