name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/action-build.yaml
    with:
      version-postfix: "-master"
      web-path-root: /${{ github.event.repository.name }}/

  github-pages:
    needs: [build]
    name: Deploy Github Pages
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/action-gh-page.yaml
    with:
      artifact-name: web
