name: Release

on:
  push:
    tags:
      - release/*
      - draft/*

jobs:
  build:
    name: Build
    uses: ./.github/workflows/action-build.yaml
    with:
      version-postfix: ""

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}, Commit ${{ needs.build.outputs.version }}
          draft: ${{ startsWith(github.ref_name, 'draft/') }}
          prerelease: false
          files: build/book-*.pdf
